version: '2'
services:
  client:
    build: ./client/
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
  server:
    build: ./server/
    ports:
      - "5005:5005"
    stdin_open: true
    tty: true
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    #command: ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --port 8080
